server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://39.107.67.145:3306/health?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: tw900516
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 39.107.67.145 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: tw900516

    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        timeout: 3000ms # 连接超时时间（毫秒）


  mail:
    username: 1569132595@qq.com
    password: cldmccsistviicae
    host: smtp.qq.com
    port: 587

  aop:
    proxy-target-class: true
    auto: true



mybatis:
  type-aliases-package: com.lyx.health.entity
  mapper-locations: classpath:Mapper/*.xml


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志



logging:
  level:
    com.steven.hotel.mapper: debug


