server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: tw900516
    driver-class-name: com.mysql.cj.jdbc.Driver


  mail:
    username: 1569132595@qq.com
    password: cldmccsistviicae
    host: smtp.qq.com




mybatis:
  type-aliases-package: com.lyx.health.entity
  mapper-locations: classpath:Mapper/*.xml



logging:
  level:
    com.steven.hotel.mapper: debug